services:
  database:
    image: postgres:18-alpine
    ports:
      - "${METADATA_DB_PORT}:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${METADATA_DB_USER}
      - POSTGRES_PASSWORD=${METADATA_DB_PASSWORD}
      - POSTGRES_DB=${METADATA_DB_NAME}
    restart: on-failure
    networks:
      - bric-a-brac-network

volumes:
  postgres_dev_data:

networks:
  bric-a-brac-network:
    name: bric-a-brac-network
    driver: bridge
