services:
  server:
    build:
      context: ..
      dockerfile: metadata/Dockerfile
    ports:
      - "${METADATA_SERVER_PORT}:8080"
    environment:
      - METADATA_SERVER_HOST=${METADATA_SERVER_HOST}
      - METADATA_SERVER_PORT=${METADATA_SERVER_PORT}
      - KNOWLEDGE_SERVER_URL=${KNOWLEDGE_SERVER_URL}
      - METADATA_DB_URL=${METADATA_DB_URL}
      - METADATA_DB_MAX_CONNECTIONS=${METADATA_DB_MAX_CONNECTIONS}
      - METADATA_DB_SKIP_MIGRATION=${METADATA_DB_SKIP_MIGRATION}
      - SQLX_OFFLINE=${SQLX_OFFLINE}
      - RUST_LOG=${RUST_LOG}
    restart: on-failure
    networks:
      - bric-a-brac-network

networks:
  bric-a-brac-network:
    external: true
    name: bric-a-brac-network
