[env]
# Metadata Database Configuration
# METADATA_DB_HOST=""
# METADATA_DB_PORT=""
# METADATA_DB_USER=""
# METADATA_DB_PASSWORD=""
# METADATA_DB_NAME=""
# METADATA_DB_URL="postgresql://{{env.METADATA_DB_USER}}:{{env.METADATA_DB_PASSWORD}}@{{env.METADATA_DB_HOST}}:{{env.METADATA_DB_PORT}}/{{env.METADATA_DB_NAME}}"
# METADATA_DB_MAX_CONNECTIONS=""
# METADATA_DB_SKIP_MIGRATION=""

# Internal Services Authentication
# INTERNAL_SERVICES_AUTH_TOKEN=""

# Metadata Server Configuration
# METADATA_SERVER_HOST=""
# METADATA_HTTP_SERVER_PORT=""
# METADATA_GRPC_SERVER_PORT=""

# Knowledge Server Configuration
# KNOWLEDGE_GRPC_SERVER_URL=""

# AI Server Configuration
# AI_GRPC_SERVER_URL=""

# SQLX
# SQLX_OFFLINE="false"
# DATABASE_URL="{{env.METADATA_DB_URL}}"

# LOGS
# RUST_LOG="warn,metadata=trace,bric_a_brac_protos=info"

[tasks]
db-config = "docker compose -f compose.db.yaml config"
db-start = "docker compose -f compose.db.yaml up --build -d"
db-stop = "docker compose -f compose.db.yaml down"
server-config = "docker compose -f compose.server.yaml config"
server-start = "docker compose -f compose.server.yaml up --build -d"
server-stop = "docker compose -f compose.server.yaml down"
