[env]
# Metadata Database Configuration
# METADATA_DB_HOST=""
# METADATA_DB_PORT=""
# METADATA_DB_USER=""
# METADATA_DB_PASSWORD=""
# METADATA_DB_NAME=""
# METADATA_DB_URL="postgresql://{{env.METADATA_DB_USER}}:{{env.METADATA_DB_PASSWORD}}@{{env.METADATA_DB_HOST}}:{{env.METADATA_DB_PORT}}/{{env.METADATA_DB_NAME}}"
# METADATA_DB_MAX_CONNECTIONS=""
# METADATA_DB_SKIP_MIGRATION=""

# Metadata Server Configuration
# METADATA_SERVER_HOST=""
# METADATA_SERVER_PORT=""

# Knowledge Service Configuration
# KNOWLEDGE_SERVER_HOST=""
# KNOWLEDGE_SERVER_PORT=""
# KNOWLEDGE_SERVER_URL="http://{{env.KNOWLEDGE_SERVER_HOST}}:{{env.KNOWLEDGE_SERVER_PORT}}"

# SQLX
# SQLX_OFFLINE="false"

# LOGS
# RUST_LOG="metadata=trace,tower_http=trace,sqlx=trace,tonic=trace"

[tasks]
db-start = "docker compose -f compose.db.yaml up --build -d"
db-stop = "docker compose -f compose.db.yaml down"
db-config = "docker compose -f compose.db.yaml config"
server-start = "docker compose -f compose.server.yaml up --build -d"
server-stop = "docker compose -f compose.server.yaml down"
server-config = "docker compose -f compose.server.yaml config"
