DROP TABLE IF EXISTS session_messages;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS edges_schemas; 
DROP TABLE IF EXISTS nodes_schemas;
DROP TABLE IF EXISTS cheers;
DROP TABLE IF EXISTS bookmarks;
DROP TABLE IF EXISTS accesses;
DROP TABLE IF EXISTS graphs;
DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS role_type;
