services:
  metadata-db:
    profiles: ["metadata", "metadata-db"]
    image: postgres:18-alpine
    ports:
      - "${METADATA_DB_PORT}:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${METADATA_DB_USER}
      - POSTGRES_PASSWORD=${METADATA_DB_PASSWORD}
      - POSTGRES_DB=${METADATA_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${METADATA_DB_USER} -d ${METADATA_DB_NAME}"]
      interval: 2s
      timeout: 5s
      retries: 5
    restart: no
    networks:
      - bric-a-brac-network

volumes:
  postgres_dev_data:
