services:
  metadata-server:
    profiles: ["metadata", "metadata-server"]
    build:
      context: ..
      dockerfile: metadata/Dockerfile
    ports:
      - "${METADATA_HTTP_SERVER_PORT}:8080"
      - "${METADATA_GRPC_SERVER_PORT}:50051"
    environment:
      - METADATA_SERVER_HOST=${METADATA_SERVER_HOST}
      - METADATA_GRPC_SERVER_PORT=${METADATA_GRPC_SERVER_PORT}
      - METADATA_HTTP_SERVER_PORT=${METADATA_HTTP_SERVER_PORT}
      - METADATA_DB_URL=${METADATA_DB_URL}
      - METADATA_DB_MAX_CONNECTIONS=${METADATA_DB_MAX_CONNECTIONS}
      - METADATA_DB_SKIP_MIGRATION=${METADATA_DB_SKIP_MIGRATION}
      - SQLX_OFFLINE=${SQLX_OFFLINE}
      - KNOWLEDGE_GRPC_SERVER_URL=${KNOWLEDGE_GRPC_SERVER_URL}
      - AI_GRPC_SERVER_URL=${AI_GRPC_SERVER_URL}
      - INTERNAL_SERVICES_AUTH_TOKEN=${INTERNAL_SERVICES_AUTH_TOKEN}
      - RUST_LOG=${RUST_LOG}
    depends_on:
      metadata-db:
        condition: service_healthy
    restart: no
    networks:
      - bric-a-brac-network
