services:
  server:
    build:
      context: ..
      dockerfile: knowledge/Dockerfile
    ports:
      - "${KNOWLEDGE_SERVER_PORT}:50051"
    environment:
      - KNOWLEDGE_SERVER_HOST=${KNOWLEDGE_SERVER_HOST}
      - KNOWLEDGE_SERVER_PORT=${KNOWLEDGE_SERVER_PORT}
      - KNOWLEDGE_DB_HOST=${KNOWLEDGE_DB_HOST}
      - KNOWLEDGE_DB_PORT=${KNOWLEDGE_DB_PORT}
      - KNOWLEDGE_DB_USER=${KNOWLEDGE_DB_USER}
      - KNOWLEDGE_DB_PASSWORD=${KNOWLEDGE_DB_PASSWORD}
      - KNOWLEDGE_DB_NAME=${KNOWLEDGE_DB_NAME}
      - KNOWLEDGE_DB_MAX_CONNECTIONS=${KNOWLEDGE_DB_MAX_CONNECTIONS}
      - KNOWLEDGE_DB_FETCH_SIZE=${KNOWLEDGE_DB_FETCH_SIZE}
    restart: on-failure
    networks:
      - bric-a-brac-network

networks:
  bric-a-brac-network:
    external: true
    name: bric-a-brac-network
