[env]
# Knowledge Database Configuration
# KNOWLEDGE_DB_HOST=""
# KNOWLEDGE_DB_PORT=""
# KNOWLEDGE_DB_USER=""
# KNOWLEDGE_DB_PASSWORD=""
# KNOWLEDGE_DB_NAME=""
# KNOWLEDGE_DB_FETCH_SIZE=""
# KNOWLEDGE_DB_MAX_CONNECTIONS=""

# Knowledge Server Configuration
# KNOWLEDGE_SERVER_HOST=""
# KNOWLEDGE_SERVER_PORT=""

# LOGS
# RUST_LOG="warn,knowledge=trace,bric_a_brac_protos=debug"

[tasks]
db-config = "docker compose -f compose.db.yaml config"
db-start = "docker compose -f compose.db.yaml up --build -d"
db-stop = "docker compose -f compose.db.yaml down"
server-config = "docker compose -f compose.server.yaml config"
server-start = "docker compose -f compose.server.yaml up --build -d"
server-stop = "docker compose -f compose.server.yaml down"
