services:
  server:
    build:
      context: ..
      dockerfile: ai/Dockerfile
    ports:
      - "${AI_SERVER_PORT}:8081"
    environment:
      - AI_SERVER_HOST=${AI_SERVER_HOST}
      - AI_SERVER_PORT=${AI_SERVER_PORT}
      - AI_OPENROUTER_API_KEY=${AI_OPENROUTER_API_KEY}
      - AI_OPENROUTER_DEFAULT_MODEL=${AI_OPENROUTER_DEFAULT_MODEL}
      - METADATA_SERVER_URL=${METADATA_SERVER_URL}
      - RUST_LOG=${RUST_LOG}
    restart: on-failure
    networks:
      - bric-a-brac-network

networks:
  bric-a-brac-network:
    external: true
    name: bric-a-brac-network
