[env]
# AI Server Configuration
# AI_SERVER_HOST=""
# AI_SERVER_PORT=""

# OpenRouter Configuration
# OPENROUTER_API_KEY=""
# OPENROUTER_DEFAULT_MODEL=""
# OPENROUTER_EMBEDDING_MODEL=""

# Internal Services Authentication
# INTERNAL_SERVICES_AUTH_TOKEN=""

# Metadata Server Configuration
# METADATA_GRPC_SERVER_URL=""

# Knowledge Server Configuration
# KNOWLEDGE_GRPC_SERVER_URL=""

# LOGS
# RUST_LOG="warn,ai=trace,bric_a_brac_protos=info"

[tasks]
server-config = "docker compose -f compose.server.yaml config"
server-start = "docker compose -f compose.server.yaml up --build -d"
server-stop = "docker compose -f compose.server.yaml down"
