[env]
# Ai Server Configuration
# AI_SERVER_HOST=""
# AI_SERVER_PORT=""

# OpenRouter Configuration
# OPENROUTER_API_KEY=""
# OPENROUTER_DEFAULT_MODEL=""

# Metadata Server Configuration
# METADATA_GRPC_SERVER_URL=""

# LOGS
# RUST_LOG="warn,ai=trace,bric_a_brac_protos=debug"

[tasks]
server-config = "docker compose -f compose.server.yaml config"
server-start = "docker compose -f compose.server.yaml up --build -d"
server-stop = "docker compose -f compose.server.yaml down"
