###
# Build
###
FROM oven/bun:1 AS builder

WORKDIR /app

COPY web-ui/package.json web-ui/bun.lock ./
RUN bun install --frozen-lockfile

COPY web-ui/ .

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_USER_ID

RUN bun --bun next build

###
# Runtime
###
FROM node:22-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000

CMD ["node", "server.js"]
